### ISSUE TITLE
Where is Banned file?

### ISSUE THREAD

**Issue by helma27** [m-byte/Cigar#19]
Excuse me, can somebody show me where is files and config that related to banned system?
I need to implemented it with forairan/Ogar server's..
Because i don't know why i always got error while use this server..
And original Ogar's has deleted the banned system, i need it right now..

Thank you :)

**Comment by m-byte** [comment]
I'm not exactly sure whet you are trying to accomplish. If you want to implement it in Ogar, you should look through the commit history and revert the commit that deleted it (in your local copy). If your issue is actually related to Cigar, feel free to reopen this issue.
