### ISSUE TITLE
Error "npm ERR!"

### ISSUE THREAD

**Issue by helma27** [m-byte/Cigar#20]
root@agario:~# npm start
npm ERR! Linux 2.6.32-042stab108.2
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! path /root/package.json
npm ERR! code ENOENT
npm ERR! errno -2

npm ERR! enoent ENOENT, open '/root/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log

Did i miss something?

**Comment by m-byte** [comment]
Did you run `npm install` first?                                                                                                                                                                                                                                                                                                                                        Gesendet von meinem BlackBerry 10-Smartphone.                                                                                                                                                                                                                Von: helma27Gesendet: Donnerstag, 9. Juli 2015 22:26An: m-byte/CigarAntwort an: m-byte/CigarBetreff: [Cigar] Error "npm ERR!" (#20)root@agario:~# npm start
npm ERR! Linux 2.6.32-042stab108.2
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! path /root/package.json
npm ERR! code ENOENT
npm ERR! errno -2

npm ERR! enoent ENOENT, open '/root/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log

Did i miss something?

—Reply to this email directly or view it on GitHub.

**Comment by helma27** [comment]
Yes, i already do that, but everytime i install it, i got these errors, but i can start Ogar's server normaly..

**Comment by helma27** [comment]
root@agario:~# npm install
npm ERR! install Couldn't read dependencies
npm ERR! Linux 2.6.32-042stab108.2
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! path /root/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno -2

npm ERR! package.json ENOENT, open '/root/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log

What should i do?

**Comment by m-byte** [comment]
You didn't cd into the Ogar directory. If you ran `git clone https...Cigar.git` right after starting your terminal, you'll have to run `cd Cigar` next and then `npm install`                                                                                                                                                                                                   Gesendet von meinem BlackBerry 10-Smartphone.                                                                                                                                                                                                                Von: helma27Gesendet: Samstag, 11. Juli 2015 15:42An: m-byte/CigarAntwort an: m-byte/CigarCc: m-byteBetreff: Re: [Cigar] Error "npm ERR!" (#20)root@agario:~# npm install
npm ERR! install Couldn't read dependencies
npm ERR! Linux 2.6.32-042stab108.2
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! path /root/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno -2

npm ERR! package.json ENOENT, open '/root/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log

What should i do?

—Reply to this email directly or view it on GitHub.
