### ISSUE TITLE
config file doesn't seem to work in windows (7)

### ISSUE THREAD

**Issue by mikjodo** [m-byte/Cigar#22]
The game server seems to run fine, and most commands work, but the cigar.exe program doesnt seem to want to load the masterserver.ini file. I tried just changing the gamemode as well as different options with no luck at all.

**Comment by XeuRun** [comment]
Use gameserver1.ini as filename for config file and place him in folder with exe

**Comment by XeuRun** [comment]
Maybe you about gameserver.ini? Use gameserver1.ini as filename for config(for each server instance other config file with suffix) and place him in folder with exe.

**Comment by m-byte** [comment]
The game mode should not be set in masterserver.ini. As @XeuRun wrote, it is set in gameserver`{id}`.ini.
