### ISSUE TITLE
How to add "Teams" or "Experimental" to work

### ISSUE THREAD

**Issue by NikoCodex** [m-byte/Cigar#26]
I keep clicking them however it doesn't seem to work, it just sends me into the same server.
What do i type in the master console to get it working?
I mean can someone explain to me how to do it? This has confused me...

**Comment by m-byte** [comment]
The easiest way of doing this at the moment is to add custom Regions. E.g. `regions = {"Experimental":1, "Teams":1, "Normal":1}` in masterserver.ini

**Comment by NikoCodex** [comment]
Sorry to challange your intellect, but there's a way without regions.
Add this to the main_out.js
Handle.setserver = function (arg) {
        if (arg != gameMode) {
             CONNECTION_URL = arg;
            gameMode = arg;
            showConnecting();
        }
    };
In index, change
onchange="setGameMode($(this).val());"
to
onchange="setserver($(this).val());"
Now update your options:
  <option value='IP:PORT'>FFA</option>
                    <option value='IP:PORT'>Teams</option>
                    <option value='IP:PORT'>Experimental</option>
Thanks for nothing.
