### ISSUE TITLE
How to change server name and add team mode

### ISSUE THREAD

**Issue by hyperlord2** [m-byte/Cigar#33]
Hi, how to change server name (defautly called Agar clone)? When I rewrite it and save changes won´t take effect. And how I can add team mode? Thak you.

**Comment by m-byte** [comment]
Hi, please download the newest version and edit https://github.com/m-byte/Cigar/blob/master/server/web/routes/index.js to change the name (`Cigar` and `Cigar skins`). If you want to edit more parts of the page, take a look at https://github.com/m-byte/Cigar/blob/master/server/web/views/game.hbs. `index.html` was never sent to the user, so I removed it to prevent confusion.

For team mode, edit gamemode[n].ini or enter `Gamemode 1` in the console.
