### ISSUE TITLE
create [region] [gamemode]

### ISSUE THREAD

**Issue by CineXMike** [m-byte/Cigar#34]
Gamemode var doesnt work id not and name not
Please look into it

**Comment by vram4** [comment]
It works fine, if you want a special gamemode, region would be ```name_of_region + gamemode``` where gamemodes are "" (for ffa), ":teams" and ":experimental".

**Comment by CineXMike** [comment]
When i say create [region] [:teams] It creates an server with gamemode experimental and i am not able to connect when i click on experimental or on teams :-1:

**Comment by vram4** [comment]
Thats because you created it in the wrong region.
>if you want a special gamemode, region would be name_of_region + gamemode where gamemodes are "" (for ffa), ":teams" and ":experimental".

**Comment by CineXMike** [comment]
No i didnt create it in wrong region because i only have 1 region.
And aigan when i  create an server with :teams it makes an server experimental (WRONG GAMEMODE)
