### ISSUE TITLE
Coordinates always spawn to 0,0

### ISSUE THREAD

**Issue by xmicro** [m-byte/Cigar#39]
No matter what you enter, it's 0, 0

**Comment by vram4** [comment]
Can you copy and paste your config here?

**Comment by xmicro** [comment]
I'm using Cigar.exe, would that be MasterServer.ini?

**Comment by vram4** [comment]
No, GameServer.ini

**Comment by xmicro** [comment]
// Ogar configurations file
// Lines starting with slashes are comment lines

// [Server]
// serverGamemode: 0 = FFA, 1 = Teams, 2 = Experimental, 10 = Tournament, 11 = Hunger Games
// serverBots: Amount of player bots to spawn (Experimental)
// serverViewBase: Base view distance of players. Warning: high values may cause lag
// leaderboardUpdateClient: How often leaderboard data is sent to the client (1 tick = 50 milliseconds)
serverMaxConnections = 64
serverPort = 443
serverGamemode = 0
serverBots = 0
serverViewBase = 1024

// [Master Server]
// ONLY CHANGE IF YOU KNOW WHAT YOURE DOING
useWithMaster = false
masterIP = "127.0.0.1"
masterCommands = false
masterUpdate = 45

// [Border]
// Border values of the map (Vanilla values are left/top = 0, right/bottom = 11180.3398875)
borderLeft = 0
borderRight = 6000
borderTop = 0
borderBottom = 6000

// [Spawn]
// Each interval is 1 tick (50 ms)
spawnInterval = 20
foodSpawnAmount = 10
foodStartAmount = 100
foodMaxAmount = 500
foodMass = 2
virusMinAmount = 10
virusMaxAmount = 50
virusStartMass = 100
virusFeedAmount = 7

// [Ejected Mass]
// ejectMass: Mass of ejected cells
// ejectMassLoss: Mass lost when ejecting cells
// ejectSpeed: Base speed of ejected cells
// ejectSpawnPlayer: Chance for a player to spawn from ejected mass
ejectMass = 12
ejectMassLoss = 16
ejectSpeed = 160
ejectSpawnPlayer = 50

// [Player]
// playerRecombineTime: Base amount of ticks before a cell is allowed to recombine (1 tick = 1000 milliseconds)
// playerMassDecayRate: Amount of mass lost per tick (Multiplier) (1 tick = 1000 milliseconds)
// playerMinMassDecay: Minimum mass for decay to occur
// playerDisconnectTime: The amount of seconds it takes for a player cell to be removed after disconnection (If set to -1, cells are never removed)
playerStartMass = 10
playerMaxMass = 22500
playerMinMassEject = 32
playerMinMassSplit = 36
playerMaxCells = 16
playerRecombineTime = 30
playerMassDecayRate = .002
playerMinMassDecay = 9
playerMaxNickLength = 15
playerDisconnectTime = 60

// [Gamemode]
// Custom gamemode settings
// tourneyAutoFill: If set to a value higher than 0, the tournament match will automatically fill up with bots after value seconds
// tourneyAutoFillPlayers: The timer for filling the server with bots will not count down unless there is this amount of real players
tourneyMaxPlayers = 12
tourneyPrepTime = 10
tourneyEndTime = 30
tourneyAutoFill = 0
tourneyAutoFillPlayers = 1


Also: how do I kick players? I copied the code from Ogar for it and pasted it in the CommandList.js but it still says invalid.

**Comment by vram4** [comment]
Everything seems fine. Are you using https://github.com/Eureka22/agar-clone or the official client? As for kicking, you have to select the id of the gameserver that you want to kick the player from first.

**Comment by xmicro** [comment]
Agar-clone.

**Comment by xmicro** [comment]
And how come when I enter master commands it says invalid command?

**Comment by m-byte** [comment]
Before running master commands, you have to select the master server (`Select 0`)

**Comment by xmicro** [comment]
But the server only starts if I use Cigar.exe, the batch files says online port 88 but they don't work.

**Comment by xmicro** [comment]
So is the coordinates a known problem? Or is it only me? How do I fix?

**Comment by xmicro** [comment]
And why doesn't the config for Cigar.exe work? It always defaults.
