### ISSUE TITLE
Why doesn't gameserver.ini work for Cigar.exe, and why can't I use master commands?

### ISSUE THREAD

**Issue by xmicro** [m-byte/Cigar#43]
When I launch Cigar.exe, the gameserver.ini changes I make don't work, I have to manually edit them every time I launch the game. And when I type master commands in, it says invalid command.

The only thing I can use is Cigar.exe, the batch files state they are working, but in fact they don't. Help?

**Comment by m-byte** [comment]
The master commands are somehthing that has already been covered multiple times. Use `Select 0` to select the master server before entering them.

gameserver.ini is in there as an example. You'll need gameserver1.ini for the first game server.

**Comment by xmicro** [comment]
What's are the region names? It keeps saying invalid.

**Comment by xmicro** [comment]
Create [Region Name] [Game mode]

What do I enter for Region Name, everything I enter says invalid.
