### ISSUE TITLE
Integrate a client

### ISSUE THREAD

**Issue by m-byte** [m-byte/Cigar#5]
As cigar is a backronym of `Completely Integrated oGAR`, we should integrate a client into it. The two options are: agar-clone and Ogar-client. Ogar-client is not done yet, so we can either go with agar-clone or wait until we are done with Ogar-client.

**Comment by Eureka22** [comment]
Can some of agar-clone's code be reused in Ogar-client? Will Ogar-client support vanilla server? @m-byte

**Comment by m-byte** [comment]
Currently, Ogar-client will support the vanilla server. Since all our additions to the protocol did not change the meaning of any packets available in vanilla ans since our additions can simply be ignored, it should work just as well with vanilla.

**Comment by vram4** [comment]
We should use agar clone for the time being then

**Comment by Eureka22** [comment]
Agreed. I will set it up after the merge is done.

**Comment by vram4** [comment]
@Eureka22 The merge with the master server?

**Comment by Eureka22** [comment]
Yes we want to make the master branch Master server. But that seems a lot of work. If no one is going to do that I will do that tomorrow :)

**Comment by vram4** [comment]
Ah okay, but i think i should be the one to do it, as i wrote it myself :)

**Comment by Eureka22** [comment]
Thanks man @varm4

**Comment by m-byte** [comment]
Nice! I was only away for a few hours, but the project is already moving along :)
Thank you, vram4!

**Comment by m-byte** [comment]
Sorry, assigned you to the wrong issue

**Comment by Eureka22** [comment]
@m-byte let me take this issue

**Comment by m-byte** [comment]
Ok

**Comment by m-byte** [comment]
Having the master server integrated, the `/info.php` problem should also go away, since the master server already comes with `/info`.

By the way, shouldn't you be able to assign issues to yourself here? I thought, contributors could do that.

**Comment by Eureka22** [comment]
Yes I am able to do that but I was using my phone. I will do self assign in the future thanks :D

**Comment by m-byte** [comment]
Ah ok :D That makes sense

**Comment by m-byte** [comment]
Btw: you might want to look into git subtree for getting your client into cigar.

**Comment by Eureka22** [comment]
@m-byte Right, but I what to do some deep integration, like a single command will run both the client and server?

**Comment by m-byte** [comment]
For Ogar-client, I am using express. This is also required for using all those neat things like passport. I will probably start integrating it later today.

**Comment by m-byte** [comment]
Please take a look at https://github.com/m-byte/Cigar/tree/Express
I don't have access to my test server right now, so there might still be errors in it. I'll clean it up tomorrow.

**Comment by m-byte** [comment]
So the branch is mostly working now. I'll add a checkdir function and then merge it into master...
You'll still have to find a solution for the gallery, though.

**Comment by m-byte** [comment]
@Eureka22 I merged the express branch. https://github.com/m-byte/Cigar/pull/15
Also, I ported the gallery to node.js: https://github.com/m-byte/Cigar/pull/16
You'll still have to do some cleanup in the client directory, though. All the php are not needed anymore, there are ".png" and ".jpg" in the skins directory, the whole gallery directory is not needed, ...
Also, the access log should probably [moved to a file](https://github.com/expressjs/morgan#log-file-rotation) as it is currently polluting the console.

**Comment by Eureka22** [comment]
@m-byte cleaned up a little bit.

**Comment by m-byte** [comment]
I also noticed: there is no favicon included.

**Comment by Eureka22** [comment]
Favicon is rendered in main_out.js :) using your cell, very cool

**Comment by m-byte** [comment]
Ok, just fixed an error :D Since you deleted the skins directory, checkdir could not get the files from that directory anymore. This resulted in the following error:
```
/user/Cigar/server/web/app.js:123
                for (var i = 0; i < files.length; i++) {
                                         ^
TypeError: Cannot read property 'length' of undefined
    at /user/Cigar/server/web/app.js:123:42
    at FSReqWrap.oncomplete (fs.js:95:15)

npm ERR! Linux 2.6.32-042stab108.5
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE
npm ERR! Cigar@1.0.0 start: `node ./server/index`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Cigar@1.0.0 start script 'node ./server/index'.
npm ERR! This is most likely a problem with the Cigar package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./server/index
npm ERR! You can get their info via:
npm ERR!     npm owner ls Cigar
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /user/Cigar/npm-debug.log
```

Now, when starting the master server, the program makes sure this directory exists and creates it if it doesn't.

**Comment by m-byte** [comment]
@Eureka22 still needs a favicon to start with:
```
Uncaught TypeError: Cannot read property 'cloneNode' of null
```

The js it complains about (line 1718):
```
var favicon = document.getElementById("favicon"),
                oldfavicon = favicon.cloneNode(true);
```

**Comment by Eureka22** [comment]
@m-byte weird, was not a problem for agar-clone, but I added a favicon now.

**Comment by m-byte** [comment]
Thanks

**Comment by m-byte** [comment]
I just realized that this is done.
