### ISSUE TITLE
windows defender flags cigar.exe as malware

### ISSUE THREAD

**Issue by mikjodo** [m-byte/Cigar#55]
Says it contains Win32/Skeeyah.C!plock.

**Comment by ryush00** [comment]
ALYac also says.

**Comment by m-byte** [comment]
I removed the exe and will not make a new one. I have no idea, how the virus (if it was not a false positive) made it into the exe, and I am very sorry for anyone this might have affected.
There will be no more exe from me in the future, as I stopped using Windows. If anyone wants to step up and maintain a binary version for Windows, let me know. We would have to figure out a way to prevent something like this from happening again.
