### ISSUE TITLE
Uggghh Skins

### ISSUE THREAD

**Issue by Pollogy** [m-byte/Cigar#562]
###  -> Skins only work when used as **NICK** wont work with <> or {} or [] 
 ----> Example skin name: Bad it wont work with <bad> or {bad} or [bad] but it will work if i put BAD in my nick name

> NOTE: Yes , they are **PNG!** and Names are all **lowercase Letters.**

**Comment by makandz** [comment]
Use MultiOgar-Edited, latest version works fine.

**Comment by Pollogy** [comment]
I am using 1.6.0 isnt that the latest?

**Comment by makandz** [comment]
Latest commit?

**Comment by TigOlBittes** [comment]
Same problem, same version. What do u mean bh LATEST Commits?

**Comment by Pollogy** [comment]
Yeah Latest Commits?

**Comment by makandz** [comment]
Download the LATEST version, not just 1.6, like the complete built version currently on download and zip.

**Comment by Unai144** [comment]
Happens the same to me and I've got the lastest MultiOgar Edited version 🤔
