### ISSUE TITLE
cannot connect to the servers ?!

### ISSUE THREAD

**Issue by eevaqueen** [m-byte/Cigar#564]
I used MultiOgar-Edited with Cigar I got this error every time.
I change the port from 5511 to 443 not work too?
the modified was in index.html and main_out.js with MultiOgar server ip

![1](https://cloud.githubusercontent.com/assets/17146668/25067673/b60c7d56-21ff-11e7-99dc-ac03c2d52d00.jpg)
![2](https://cloud.githubusercontent.com/assets/17146668/25067674/b893c3a4-21ff-11e7-89c3-cd6e16e369b0.jpg)
![3](https://cloud.githubusercontent.com/assets/17146668/25067675/bb3a2fa8-21ff-11e7-80a8-7dc03806fe82.jpg)
@MastaCoder plz help! also the server work with agario website normly ????

**Comment by makandz** [comment]
Open the console, paste what you see in there.

**Comment by malekksa505** [comment]
Edit index for gamemode

**Comment by eevaqueen** [comment]
@malekksa505 I edit that in gameserver.ini MultiOgar files,now you need me to edit gamemode in index file of cigar?,Because I can't see any code for gamemode id ???

**Comment by eevaqueen** [comment]
@MastaCoder 
| [INFO] 419 bad words loaded
| [WARN] User account "Local Administrator" disabled
| [WARN] User account "Local Moderator" disabled
| [WARN] User account "Local User" disabled
| [INFO] 0 user records loaded.
| [INFO] 0 IP ban records loaded.
| [INFO] MultiOgar-Edited 1.6.0 - An open source multi-protocol ogar server
| [INFO] WebSocket: ws
| [INFO] Started stats server on port 441
| [INFO] Listening on port 442
| [INFO] Current game mode is Experimental
  __  __       _ _   _  ___                        _____    _ _ _           _    _   __    ___
 |  \/  |_   _| | |_(_)/ _ \  __ _  __ _ _ __     | ____|__| (_) |_ ___  __| |  / | / /_  / _ \
 | |\/| | | | | | __| | | | |/ _` |/ _` | '__|____|  _| / _` | | __/ _ \/ _` |  | || '_ \| | | |
 | |  | | |_| | | |_| | |_| | (_| | (_| | | |_____| |__| (_| | | ||  __/ (_| |  | || (_) | |_| |
 |_|  |_|\__,_|_|\__|_|\___/ \__, |\__,_|_|       |_____\__,_|_|\__\___|\__,_|  |_(_)___(_)___/
![waaaaaaaaaaaaa](https://cloud.githubusercontent.com/assets/17146668/25072813/21f173ea-228d-11e7-9c1b-8f39e6ab93da.jpg)

**Comment by gyeyoqu** [comment]
@eevaqueen paste a screenshot that you can see on Google Console (Press F12 and console tab)

**Comment by eevaqueen** [comment]
@MastaCoder @gyeyoqu 

(index):1 WebSocket connection to 'wss://52.243.48.98:445/' failed: WebSocket is closed before the connection is established.
log.js:6 [INFO] Connecting to wss://52.243.48.98:445..
main_out.js:326 WebSocket connection to 'wss://52.243.48.98:445/' failed: Error in connection establishment: net::ERR_CONNECTION_TIMED_OUT

**Comment by makandz** [comment]
Port doesn't seem to be opened if it's timing out. Find out how to port forwards on your provider. (IP could be wrong as well) This is because it's timing out, not a server or client bug but how you configured it.
