### ISSUE TITLE
Force Nick

### ISSUE THREAD

**Issue by Logan7432** [m-byte/Cigar#566]
What would I add to the code to make it so people are forced to pick a nickname?

**Comment by ZfsrGhS953** [comment]
@MastaCoder Server-sided.

**Comment by Logan7432** [comment]
@ZfsrGhS956 No, I see a bunch of other sites that have it. WHEN you press play it says bad Nick or something and won't let u play

**Comment by makandz** [comment]
Yes but then it takes a good 3 seconds to bypass that.

Also to get that, just do if (nickname == false) return alert("no nick"); (Finding where to put this really isn't hard.)

**Comment by Logan7432** [comment]
@MastaCoder Everywhere I put that line of code it screws up my entire site. I've been trying to implement it into the main_out.js Help, This is not easy to find lol

**Comment by makandz** [comment]
It is if you knew how to program. Instead of wasting time trying to find the lines and guessing, learning how to program would be a better option for you.

**Comment by Logan7432** [comment]
@MastaCoder I don't have time in my live right now to be learning how to code, I have a lot of school.

**Comment by Luka967** [comment]
Guessing for a few days is worse than learning basic JS in a few days then guessing for a few hours.

**Comment by Logan7432** [comment]
@Luka967 I guess, lol. But can please know where to put this?

**Comment by makandz** [comment]
main_out.js, just keep pasting from line to line until it works

**Comment by Logan7432** [comment]
@MastaCoder Thx
