### ISSUE TITLE
How to make locked names

### ISSUE THREAD

**Issue by AlexHGaming** [m-byte/Cigar#568]
I want to know how to make your very own locked names.
An idea of design could be using a prompt box.
So if user enters PASSWORD (no username)
this will allow them to use the locked name
else reject the request.

So if I wanted my locked name to be AlexHGaming
When clicking play, it shows a prompt box asking for a password (all passwords are stored in arrays)
if password is entered correctly
Let player play
else reject request and bring to main menu, showing a confirm box saying 'Incorrect password'
This is my dream to have wanted to be true lol

**Comment by makandz** [comment]
Server sided :D

**Comment by AlexHGaming** [comment]
@MastaCoder I don't understand how it's server sided

**Comment by makandz** [comment]
Where are the passwords going to be stored?

**Comment by AlexHGaming** [comment]
through client files?

**Comment by makandz** [comment]
And you're just going to send the passwords to all the clients that load the page? lmao

**Comment by AlexHGaming** [comment]
@MastaCoder do you know where in the server files I can add the function?
And what lines I need to place them on?

**Comment by makandz** [comment]
You'd need SQL if you want to store them, then you'd also need to send a packet or something back to the client or have the client send the password in a different packet.

**Comment by Logan7432** [comment]
Ita server sided, look at old cigar server. Cigar sever had this request but its very outdated.

**Comment by gyeyoqu** [comment]
@MastaCoder client side is possible whit localstorage and simple array

**Comment by makandz** [comment]
@gyeyoqu And it's also very simple to bypass.

**Comment by Logan7432** [comment]
@MastaCoder I'm pretty sure people don't just sit there and try and bypass a nickname on agario.

**Comment by makandz** [comment]
It literally takes 2 seconds to bypass the name block things. The passwords going to be stored inside of the client files, simple look at the client files and they can find it. Even if you encrypt, your encrypt salt and how you did it will be there to.

This is security you're talking about, not a simple just hope they don't do it. If they do it, the damage will be done. (Pretend to be you, scam out other people, pull others away from the site.)

It's ridiculous how nobody is willing to put in work for a key element of security and just want something to work.

**Comment by zettabyte918** [comment]
you only need ajax and basics php skills!!!!!
