### ISSUE TITLE
Map

### ISSUE THREAD

**Issue by Logan7432** [m-byte/Cigar#569]
When I'm trying to add the map the map picture itself won't come up, I got the dot working and moving correctly though

**Comment by gyeyoqu** [comment]
@Logan7432 give me your agar link and i will help u

**Comment by makandz** [comment]
Nope.

**Comment by Logan7432** [comment]
@gyeyoqu http://bubbles.kozow.com/ Thanks

**Comment by Logan7432** [comment]
@MastaCoder Nope what?
