### ISSUE TITLE
question to make a function

### ISSUE THREAD

**Issue by AlexHGaming** [m-byte/Cigar#571]
How can you make a little tickbox next to 'smooth render' that says 'lower name', which gives the user a lowername. I made the mass lower, but that is always. I just want a function that allows the lower name and i will edit it to my standards.

**Comment by makandz** [comment]
Copy paste the current checkbox structure, go to main_out.js and add wHandle.... and the function. Everything is there, just copy and paste to learn.

**Comment by AlexHGaming** [comment]
Where's the checkbox structure? Sorry for annoying you :P

**Comment by makandz** [comment]
Ctrl + F is your friend.

**Comment by AlexHGaming** [comment]
It always has been.
