### ISSUE TITLE
Cannot run Xampp Apache Server at the same time as WebSocket MultiOgar server

### ISSUE THREAD

**Issue by LemonDoo** [m-byte/Cigar#572]
They both use port 443, so I seem to not be able to get them to run at the same time.

If I just run the apache server from xampp control panel, it tells me there is no server to run (it gives the HTML page that looks like a blank agar.io canvas.)

If I just run the MultiOgar server, I cannot run the Xampp apache server (says port is already in use), and therefore localhost is blank.

**Comment by ItzLevvie** [comment]
Your server port needs to be different from your web server port..

You can change this in the gameserver.ini

**Comment by LemonDoo** [comment]
sorry, that does not seem to work. I changed the gameserver.ini port to 446 and it now says the server is not running when i go on localhost (blank template page for agar.io)
