### ISSUE TITLE
GameServer Uses Different Port than Apache Server - still doesn't work

### ISSUE THREAD

**Issue by LemonDoo** [m-byte/Cigar#573]
I changed the gameserver.ini port to 446 and it now says the websocket server is not running when i go on localhost home page (blank template page for agar.io) after I run the Apache Server from Xampp.

Here is what it shows when I run both Apache and MultiOgar:
![image](https://cloud.githubusercontent.com/assets/18073605/26179374/5ce4e35e-3b9e-11e7-97ff-57dcbfa80baa.png)

**Comment by plazo123** [comment]
have you changed https://github.com/CigarProject/Cigar/blob/master/www/index.html#L58
port to ?

**Comment by LemonDoo** [comment]
THat is still 443, but it should be as my Apache server that hosts Cigar is supposed to be 443. 

My WebSocket is 446

**Comment by makandz** [comment]
Make sure the client is connecting to 443 (or any other port you set it to) and your ports are open.

**Comment by plazo123** [comment]
well you need to change your index to your port to
