### ISSUE TITLE
how can i 

### ISSUE THREAD

**Issue by plazo123** [m-byte/Cigar#574]
how can i add a agar.io extension to cigar

ogario any vers

**Comment by makandz** [comment]
Port over the code from them to work with Cigar? It's not easy I hope you realized for someone that might not know JavaScript..

**Comment by plazo123** [comment]
how ive got ,y own client without cigar
[this] (www.cytclan.tk)

**Comment by plazo123** [comment]
i want it to conntact with multiogar edited chat commands
