### ISSUE TITLE
Port Issue! Still not fixed (please don't just randomly resolve when it isn't resolved)

### ISSUE THREAD

**Issue by LemonDoo** [m-byte/Cigar#575]
![image](https://cloud.githubusercontent.com/assets/18073605/26250046/be7b0706-3ce3-11e7-8963-9a735d2d5a22.png)

When I run the Apache Xampp server that contains Cigar in the htdocs (with line 183 beyond changed with added Regex, as per Luka's request), it FAILS because I am running MultiOgar on the same port, 443.

Therefore, Xampp Apache servers still CANNOT run together with the WebSocket MultiOgar servers. Why is this the case?? Should the ports for the two servers _be different?_ **I keep getting conflicting answers!**

Here is the MultiOgar Server, and what happens when I run BEFORE the apache server is started.

![image](https://cloud.githubusercontent.com/assets/18073605/26250138/149c7fa2-3ce4-11e7-8eb1-60f0f853a371.png)

I don't know how to get both to run together so that I can play this on my localhost! Please help!

**Comment by plazo123** [comment]
realy here


dont use xxam run server go to http://plazo.esy.es/www/  click on private and play :)

**Comment by plazo123** [comment]
or change your gameserver.ini port t 8880

then run xxam

then change your port in index.html
to 8880 done :))))))))))

**Comment by plazo123** [comment]
#573

**Comment by ItzLevvie** [comment]
Since Apache uses port 443, you'll have to change your MultiOgar server port to a different number (like 3814 or something else)

**Comment by plazo123** [comment]
but he dose not change the index.html t pory 3814 two

**Comment by makandz** [comment]
1. You're using an edited version of MultiOgar-Edited which we will not be provided support for.
2. The error is literally written right there, are you really that incapable of understanding the error?
 - Your game is on port 443.
 - XAMPP is literally telling you 443 is busy with Node.

Ever thought of maybe changing the port?

**Comment by plazo123** [comment]
@MastaCoder  mister coder

**Comment by plazo123** [comment]
Help me :0
