### ISSUE TITLE
Are skins cached?

### ISSUE THREAD

**Issue by 253153** [m-byte/Cigar#581]
Are skins cached or redrawn every frame? If they are cached, I'd like to know where in the code (in main_out.js) it's done

**Comment by Luka967** [comment]
Only the raw skin images are cached, and it's done on-demand - a skin is downloaded only if a cell has that skin.
[Here](https://github.com/CigarProject/Cigar/blob/master/www/assets/js/main_out.js#L1119-L1132) is a POST request for `checkdir.php` to index all skin filenames
[Here](https://github.com/CigarProject/Cigar/blob/master/www/assets/js/main_out.js#L1375-L1378) the client actually downloads the skin
