### ISSUE TITLE
Minimap Support

### ISSUE THREAD

**Issue by 253153** [m-byte/Cigar#582]
I would like to request minimap support, I know it is a commonly requested feature, is there any chance of this happening?

**Comment by makandz** [comment]
At the moment, no.

**Comment by 253153** [comment]
Ok I wrote one then, to make it work put it  after line 887 in the drawGrid function in main_out.js (tested and it works). Cheers!

        if (playerCells && playerCells.length > 0)
        {
            ctx.restore();
            ctx.save();
            var fx = width / 2000;
            var fy = height / 2000;
            var mmx = (playerCells[0].x * 0.1) / fx;
            var mmy = (playerCells[0].y * 0.1) / fy;
            ctx.fillStyle = "rgba(0,0,255,0.5)"; // minimap background color

            ctx.fillRect (canvasWidth - 220, canvasHeight - 220, 200, 200);
            ctx.restore();
            ctx.save();
            ctx.fillStyle = "rgba(0,255,0,0.9)";
            ctx.fillRect (canvasWidth - 230 + mmx, canvasHeight - 230 + mmy, 20, 20);
            ctx.restore();
            ctx.save();
        }

**Comment by malekksa505** [comment]
@deniskrop

it has been tried and placed in a file main_out  a line 888  but does not work
