### ISSUE TITLE
How to make level system and account ?

### ISSUE THREAD

**Issue by ChamForever** [m-byte/Cigar#583]
How?
Write to me please the code on the lvl or on the account

**Comment by ChamForever** [comment]
How to ?
Client : Cigar
Server : MultiOgar

**Comment by ArixProject** [comment]
like agarix.xyz ?

**Comment by makandz** [comment]
Duplicate. This requires server changes.

**Comment by zettabyte918** [comment]
Its easy u can do it with php and mysql like me http://agar.tn

**Comment by suprix** [comment]
@hossem123 can u add me on skype boki_petko to show me exactly how to make it?

**Comment by zettabyte918** [comment]
```php
if ($result->num_rows > 0) {
	while ($row = $result->fetch_assoc()) {
		
		
		if ($row['xp'] + $mass >= $row['xpneed']) {
			$sql = "UPDATE users SET level = (level + 1), xp = ($mass / 4), xpneed = (xpneed + 1330) WHERE oauth_uid = $id";
			$update = $db->query($sql);						
			
		} else {
			
			$za = "UPDATE users SET xp = (xp + $mass) WHERE oauth_uid = $id";
			$up = $db->query($za);				
			
		}
	}
}
```
this is my leveling system @suprix

**Comment by suprix** [comment]
@hossemThecoder yeah but i still need some help. Could you add me?

**Comment by zettabyte918** [comment]
Idon't use skype maybe discord ?

**Comment by suprix** [comment]
sure, my discord is Suprix#2446

**Comment by zettabyte918** [comment]
@suprix https://discordapp.com/invite/Suprix#2446 ?
