### ISSUE TITLE
Scaling calculating Formula 

### ISSUE THREAD

**Issue by Gamedevolop** [m-byte/Cigar#592]
Edited, and answered

**Comment by Ravi007Gaming** [comment]
Whats your game?

**Comment by Gamedevolop** [comment]
Hi @Ravi007Gaming 

The game is for the classic Agario FiFFA, Thank you bro
I found this code on the /js/main_out.js but I still not yet I quite understand it fully, 
example on the  function canvasResize() how do you calculate it, if you know the resolution screen (1920, 1080)
 canvasWidth = wHandle.innerWidth; >>>>>>>not sure how to calculate this
 canvasHeight = wHandle.innerHeight; >>>>>>>not sure how to calculate this


Another thing in the function viewRange() {do we really need to multiply (ratio * zoom)  if we not gonna use the feature of hand mouse wheel zoom?

And on the function drawGameScene() {
} else { im not really sure for what is the calcutation bellow 
  | nodeX = (29 * nodeX + posX) / 30;
  | nodeY = (29 * nodeY + posY) / 30;

the original code sorce==============================
[https://github.com/CigarProject/Cigar/blob/master/www/assets/js/main_out.js](url)

function canvasResize() {
  | window.scrollTo(0, 0);
  | canvasWidth = wHandle.innerWidth;
  | canvasHeight = wHandle.innerHeight;
  | nCanvas.width = canvasWidth;
  | nCanvas.height = canvasHeight;
  | drawGameScene()
  | }
  |  
  | function viewRange() {
  | var ratio;
  | ratio = Math.max(canvasHeight / 1080, canvasWidth / 1920);
  | return ratio * zoom;
  | }
  |  
  | function calcViewZoom() {
  | if (0 != playerCells.length) {
  | for (var newViewZoom = 0, i = 0; i < playerCells.length; i++) newViewZoom += playerCells[i].size;
  | newViewZoom = Math.pow(Math.min(64 / newViewZoom, 1), .4) * viewRange();
  | viewZoom = (9 * viewZoom + newViewZoom) / 10;
  | }
  | }
  |  
  | function drawGameScene() {
  | var a, oldtime = Date.now();
  | ++cb;
  | timestamp = oldtime;
  | if (0 < playerCells.length) {
  | calcViewZoom();
  | var c = a = 0;
  | for (var d = 0; d < playerCells.length; d++) {
  | playerCells[d].updatePos();
  | a += playerCells[d].x / playerCells.length;
  | c += playerCells[d].y / playerCells.length;
  | }
  | posX = a;
  | posY = c;
  | posSize = viewZoom;
  | nodeX = (nodeX + a) / 2;
  | nodeY = (nodeY + c) / 2
  | } else {
  | nodeX = (29 * nodeX + posX) / 30;
  | nodeY = (29 * nodeY + posY) / 30;
  | viewZoom = (9 * viewZoom + posSize * viewRange()) / 10;
  | }
