### ISSUE TITLE
Cigar isnt loading

### ISSUE THREAD

**Issue by Gigabyte918** [m-byte/Cigar#596]
![image](https://user-images.githubusercontent.com/17459204/28091900-54bd9fae-6646-11e7-82ac-7a33bc44ad59.png)
The page isnt loading i am using xampp with port 85 and 7251

**Comment by freaky767** [comment]
I use WAMPServer and it works totally fine..

**Comment by Gigabyte918** [comment]
ok when i reinstall xampp the cigar working fine
