### ISSUE TITLE
Why don't you guys modularize your main js file?

### ISSUE THREAD

**Issue by kevindhu** [m-byte/Cigar#597]
It's super hard to read and seems it could be way more efficient and easier on the eyes if you just use commonJS etiquette to modularize the code and export it via browserify. Am I not wrong for thinking this way?

**Comment by Luka967** [comment]
This was an obfuscated script from agar.io. It was made to be as compact as possible to minimize CPU overhead. The actions it's dealing with are too simple that doing them in procedural style is better than going object-oriented everywhere.
