### ISSUE TITLE
Read The Last Comment !!!HELP!!!

### ISSUE THREAD

**Issue by Pollogy** [m-byte/Cigar#600]
SOLVED

**Comment by Mr-BrockLee** [comment]
@MastaCoder

**Comment by hossemThecoder** [comment]
easy ! line 764
```js
if (showDarkTheme) {
                ctx.fillStyle = $("#color picker").val();
                ctx.globalAlpha = .05;
                ctx.fillRect(0, 0, canvasWidth, canvasHeight);
                ctx.globalAlpha = 1;
            }
```
this just to understand how its work .

**Comment by SAV-404** [comment]
like gota?

**Comment by MiraMiPalo** [comment]
in main_out.js line868

ctx.fillStyle = showDarkTheme ? "#111111" : "#F2FBFF";

change "#F2FBFF"
 for  document.getElementById("the id").value

**Comment by Mr-BrockLee** [comment]
@MiraMiPalo  what do i do in index.html so i can get color picker

**Comment by MiraMiPalo** [comment]
input type="color" id="The same id of main_out.js"/> 

or try this  https://www.youtube.com/watch?v=eu1KQLOEa10

**Comment by ArixProject** [comment]
@MiraMiPalo don't working

**Comment by Mr-BrockLee** [comment]
@MiraMiPalo  IDk Help

**Comment by Pollogy** [comment]
@MiraMiPalo Thx Got it to work

**Comment by Pollogy** [comment]
XD

**Comment by MiraMiPalo** [comment]
@ArixProject  
 find this line in your main_out.js    `ctx.fillStyle = showDarkTheme ? "#111111" : "#F2FBFF";`
and change for this    `ctx.fillStyle = showDarkTheme ? "#111111" : document.getElementById("background").value;`
in index.html add this line `<input type="color" id="background" value="#111111">
`
![vawhq9k](https://user-images.githubusercontent.com/25539632/30005728-5f86e2aa-90ae-11e7-9822-30baf8516213.png)

**Comment by Pollogy** [comment]
@MiraMiPalo How Crown????

**Comment by zettabyte918** [comment]
@MiraMipalo try this to get crown https://github.com/hossemThecoder/Cigar

**Comment by ArixProject** [comment]
@MiraMiPalo how to make virus cell ?

**Comment by Pollogy** [comment]
@MiraMiPalo  How to set default color in colorpicker

**Comment by MiraMiPalo** [comment]
@Mr-BrockLee  just add  `value="here default color that you want"`

**Comment by Pollogy** [comment]
@MiraMiPalo Thx and Help me fix cigar its not connecting to server i get this in console" WebSocket connection to 'wss://server1-jodal278162.codeanyapp.com:4433/' failed: Error in connection establishment: net::ERR_SSL_PROTOCOL_ERROR" I tried reinstalling (IT WORKS ON AGARIO CLIENT THO)

**Comment by MiraMiPalo** [comment]
@Mr-BrockLee  idk bro, but the server work in my client
![123123](https://user-images.githubusercontent.com/25539632/30235527-cfdce67a-94ce-11e7-85a0-3f4732435672.png)

**Comment by MiraMiPalo** [comment]
@Mr-BrockLee  don't have more errors?

**Comment by Pollogy** [comment]
@MiraMiPalo Nope  Idk why i try many clients still no work

**Comment by ChamForever** [comment]
@MiraMiPalo thanks :+1:

**Comment by Pollogy** [comment]
@ChamForever Whats ur site
