### ISSUE TITLE
lag.

### ISSUE THREAD

**Issue by SAV-404** [m-byte/Cigar#601]
might this is not related to this project..but please read this and be helpful ?!
---> i want to make the cell render of agario v72 looks like this project...

**Comment by SAV-404** [comment]
@MastaCoder can you help?

**Comment by zettabyte918** [comment]
v72 hard to read

**Comment by SAV-404** [comment]
well..i agree with you in this point @hossemThecoder .

**Comment by SAV-404** [comment]
Mr.@hossemThecoder  i really made it.. look :
small size :
![2017-09-01_173514](https://user-images.githubusercontent.com/26459304/29979108-128657d8-8f3c-11e7-8443-4670fd50604d.png)
big size : 
![2017-09-01_173602](https://user-images.githubusercontent.com/26459304/29979111-17fe90c2-8f3c-11e7-9795-f4c6146cba42.png)

**Comment by SAV-404** [comment]
now How do I fix lag?

**Comment by zettabyte918** [comment]
![capture](https://user-images.githubusercontent.com/18426424/29995104-0118093c-8fe2-11e7-91fb-a56d2ab039b2.PNG)
 change  0.1 to 0.4  and "lineWidth" to 10 then say goodbye lag

**Comment by SAV-404** [comment]
Mr.@hossemThecoder tell me please..from where did you got this project...can you give it to me please??
it looks different.

**Comment by Pollogy** [comment]
@SAV-404 Whats ur site

**Comment by SAV-404** [comment]
nooh..i did not hosted it
