### ISSUE TITLE
setNick is not defined

### ISSUE THREAD

**Issue by Mesare** [m-byte/Cigar#608]
Hey, I am trying to add some other stuff and for some reason, I am getting this errors:
![image](https://user-images.githubusercontent.com/34003001/33240377-55af57e6-d2b5-11e7-9428-73a64058305d.png)
Could anyone help me with this? Thanks.

**Comment by CalvinDKHD** [comment]
"Connect" and "SetNick" is not defined, you can see where the problem is
occuring to the right where is says 183 which means line 183 and so on

**Comment by ghost** [comment]
wow Calvin ??? :0

**Comment by Luka967** [comment]
We can't help you with this few details. At least post a part of, or the entirety of your main_out.js.
