### ISSUE TITLE
How to run OpenAgar

### ISSUE THREAD

**Issue by Faris90** [m-byte/Cigar#609]
How could I connect OpenAgar on this client

**Comment by ZfsrGhS953** [comment]
@Faris90 There are three problems with that:
1. ClosedAgar isn't compatible with Cigar's protocol.
2. ClosedAgar is closed source. So not only they aren't compatible, we don't know what the hell ClosedAgar's protocol is at all.
3. ClosedAgar looks like a very suspicious server to me. It may contain malware. So if even if you somehow got ClosedAgar to work with Cigar, I'm afraid that you have malware now.
