### ISSUE TITLE
chat

### ISSUE THREAD

**Issue by suprix** [m-byte/Cigar#610]
This is when I'm on start page (before i enter the game)
![image](https://user-images.githubusercontent.com/24485754/33291169-3a9fdcf8-d3c5-11e7-8a3f-4fda3d98e18b.png)
And this is when I press play. I can chat but I don't see what I write...
![image](https://user-images.githubusercontent.com/24485754/33291199-50107cc8-d3c5-11e7-889c-4149287061f6.png)

**Comment by ZfsrGhS953** [comment]
@suprix First of all, provide your website link so that I can look what's the problem in your code.

**Comment by Luka967** [comment]
Wrong repo.

**Comment by ghost** [comment]
@suprix Have u tried changing the chat background color ? or try changing message color ...
Find this `var chatText = new UText(18, '#666666');`  in the mainout.js and try chaning it to lighter color...
