### ISSUE TITLE
virus

### ISSUE THREAD

**Issue by suprix** [m-byte/Cigar#611]
How to make so no one can't go trough virus and how can I add skin to a virus?
I tried all solutions that are given in last issues but non of them worked!

**Comment by CodeFlush** [comment]
Point 1) I believe that is Serversided
Point 2) If it is about the chat, I need the link to see if I can reproduce and the only thing I can think of is that the Hide Chat is clicked in Settings
Point 3) I dont know about virus skins, sorry

**Comment by suprix** [comment]
what the actual fuck are you talking about? XD where did I mentioned the chat lmfao? XDD
anyway, I fixed virus so no one can't go trough it but I need now virus skins only
welp thanks for ur time

**Comment by ghost** [comment]
@suprix  NVM

**Comment by ZfsrGhS953** [comment]
@suprix Server sided...
