### ISSUE TITLE
HELP! GLitch, Help pleasse!

### ISSUE THREAD

**Issue by FrancoBM12** [m-byte/Cigar#616]
![image](https://user-images.githubusercontent.com/36641683/36572950-7464316a-180c-11e8-8563-462fd4f5ba7d.png)

**Comment by Agarian** [comment]
What are you trying to connect to?

**Comment by TopoR1** [comment]
Do not use more OgarUnlimited, it's obsolete and is not supported by anyone else!

**Comment by Faris90** [comment]
Use ogarul.surge.sh for ogar unlimited
