### ISSUE TITLE
styling

### ISSUE THREAD

**Issue by Faris90** [m-byte/Cigar#620]
How do I make my client look like this?
![image](https://user-images.githubusercontent.com/24720470/59634318-20f7e080-9114-11e9-8a15-3e205654580d.png)

**Comment by ghost** [comment]
Seeing as Ogar and Cigar have been abandoned for a long time, I'd say the only way you'll get anything out of using this is by updating it yourself.

**Comment by Luka967** [comment]
I'm pretty sure the source of OpenAgar's client is still out there, somewhere.
Apart from that, we don't really help out with broad or vague problems like this one; we answer straightforward questions or try resolving issues when people have trouble setting up.
With that said, compare where Cigar and that client differ when it comes to style, and finding out how you can change it.
If you want quick answers, you can also reach out to people in this Discord server: https://discord.gg/XcKgShT
