### ISSUE TITLE
Rename to cigar

### ISSUE THREAD

**Issue by m-byte** [m-byte/Cigar#7]
There are still lots of files and classes named Ogar. Should we rename them or leave them in their current state?

**Comment by Eureka22** [comment]
It's okay because Cigar = Ogar + client. I suggest we leave them their current state. That also shows respect to Ogar's authors.

**Comment by m-byte** [comment]
:+1:
I just added a section to the readme to show the difference between Cigar and Ogar.

**Comment by m-byte** [comment]
I think, this can be closed...
