### ISSUE TITLE
Master server

### ISSUE THREAD

**Issue by m-byte** [m-byte/Cigar#8]
Should we make the master server default server for Cigar?

**Comment by Jackster35** [comment]
Yes, isn't that what shows statistics and stuff?

**Comment by m-byte** [comment]
@Jackster35 I didn't even think about that. But yeah.. That's one more reason to do it.

@Eureka22 what do you think?

**Comment by Eureka22** [comment]
@m-byte I think it doesn't matter, after all we can choose GameServer or MasterServer by passing parameters to that. 

As for the statistics, we can use a webpage like admin page to show all the statistics and to input commands. Only admin can view and manage that webpage.

**Comment by m-byte** [comment]
Currently, MasterServer is a separate branch. I think, there are already more than enough branches out there with Ogar/master, Ogar/MasterServer and Cigar/master. So I would suggest merging Cigar/MasterServer into Cigar/Master.

**Comment by Eureka22** [comment]
@Jackster35 That will be the best.

**Comment by Jackster35** [comment]
Very nice idea guys! Look forward to seeing your results, plus, I'll be sure to beta test it. Our private server site is very big with around 100 users consistently

**Comment by Eureka22** [comment]
@m-byte merging the latest one with MasterServer seems a lot of work though

**Comment by m-byte** [comment]
I know. That's why I'd like to get that done before we add features to this repo.
